### ISSUE TITLE
Comentarios portafolio

### ISSUE THREAD

**Issue by FabianBravoA** [GloriaMoraga/Portafolio#14]
Excelente portafolio, quizá es un poco de trampa dado que eres diseñadora.
Quizá una sección para tus habilidades no estaría mal agregar. Así como también links a tu github completo, linkedin y demás enlaces a tu información.

**Comment by GloriaMoraga** [comment]
Muchas Gracias Fabian.
De hecho, ya tenía avanzado lo de las habilidades y los links, solo que no había hecho un push y actualizado el deploy ( olvidadiza sorry), ahora lo hice asi que ya esta actualizado el Portafolio, aunque aun no me convencen algunas cosas de esa seccion, asi que pretendo cambiarlas pero para después de los desafíos, tambien me falta añadir mis trabajos que he realizado en laboratoria, lo hare lo mas pronto posible.
Muchas gracias por tu feedback, seguiré trabajando para mejorar el portafolio.
